In [30]:
import pandas as pd


df = pd.read_csv('data/mountain_dataset.csv', converters={'marker': eval})

In [31]:
df.head()

                                                text      marker
0  A visit to a science museum for hands-on learn...          []
1  Voice surface coach set democratic time year. ...          []
2  Parent according maybe activity activity finis...          []
3  A visit to a sculpture garden with intriguing ...          []
4  The Julian Alps in Slovenia offer pristine lak...  [(11, 15)]

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1584 entries, 0 to 1583
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     1584 non-null   str
 1   marker   1584 non-null   object
 2   markers  1584 non-null   object
dtypes: object(2), str(1)
memory usage: 37.3+ KB

In [34]:
def divide_markers(text, markers):
    divided_markers = []
    
    for start, end in markers:
        
        # Extract the mountain name
        mountain_name = text[start:end]

        # Split the mountain name into individual words
        words = mountain_name.split(" ")

        # Generate divided markers for each word
        for word in words:
            word_start = text.find(word, start)
            word_end = word_start + len(word)
            divided_markers.append((word_start, word_end))

    
    return divided_markers


df['markers'] = df.apply(lambda row: divide_markers(row['text'], row['marker']), axis=1)

In [35]:
df.head()

                                                text      marker     markers
0  A visit to a science museum for hands-on learn...          []          []
1  Voice surface coach set democratic time year. ...          []          []
2  Parent according maybe activity activity finis...          []          []
3  A visit to a sculpture garden with intriguing ...          []          []
4  The Julian Alps in Slovenia offer pristine lak...  [(11, 15)]  [(11, 15)]

In [37]:
df['mountain_count'] = df['markers'].apply(len)

In [46]:
df['mountain_count'].value_counts()

mountain_count
0    1358
2     127
1      73
3      25
5       1
Name: count, dtype: int64

In [39]:
def get_mountains(row):
    text, loc_markers = row['text'], row['markers']
    return [text[i:j] for i, j in loc_markers]

In [41]:
mountain_record = df[df['mountain_count'] >= 1].iloc[1]
print(mountain_record.text)

mountains = get_mountains(mountain_record)
print(f"Observed moutnains: {mountains}")

The Dolomites in Italy are famous for their unique limestone formations.
Observed moutnains: ['Dolomites']

In [44]:
mountains = df.apply(get_mountains, axis=1)

mountain_sub_titles = []

for mountain_title in mountains.to_list():
    for sub_title in mountain_title:
        mountain_sub_titles.append(sub_title)

pd.Series(mountain_sub_titles).value_counts()

Mountains       82
Mount           45
Alps            34
Andes           23
Himalayas       19
Range           12
Taurus          12
Everest          9
Rhodope          9
Appalachian      8
Rocky            8
Shan             7
Fuji             7
Kilimanjaro      7
Scandinavian     7
Kunlun           5
Denali           5
Rainier          5
Sierra           5
Olympus          5
Carpathian       4
Tatra            4
Blue             4
Ridge            4
Cascade          4
Tien             4
Brooks           4
Great            4
Dividing         4
Atlas            4
Patagonian       4
Drakensberg      4
Dolomites        3
Tian             3
Rwenzori         3
Nevada           3
mountains        3
Elbrus           3
Apennine         3
Cook             3
Ural             3
St.              2
Helens           2
Madre            2
Occidental       2
Kenya            2
Columbia         2
Icefield         2
Dolomite         1
Eiger            1
K2               1
Logan            1
Name: count, dtype: int64